name: flutter_stacked_navbar
description: "Flutter Stacked Navbar is a customizable and flexible navigation bar for Flutter applications, designed to work seamlessly with the Stacked architecture."
version: 0.0.1
homepage: https://github.com/Shebo-247/flutter_stacked_navbar

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
